- name: Add Openshift Inventory
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - vars/vars.yml   
    
  tasks:    
  - name: Prepare ansible runner host
    include_tasks: tasks/prepare_ansible_runner.yml
    when: not skip_ansible_runner | bool  
      
  - name: Login ocp
    include_tasks: tasks/login-ocp.yml
  
  - name: Query cluster name if not defined
    include_tasks: tasks/query-cluster-details.yml
    when: cluster_name | length < 1 

  - name: Create proxy config cm if applicable
    include_tasks: tasks/create-proxy-config-cm.yml   

  - name: Get SA token
    include_tasks: tasks/create-service-account.yml 

  - name: Add Openshift Inventory of {{ cluster }} on Ansible Tower
    vars:
      cluster: "{{ cluster_name if cluster_name_query is undefined else cluster_name_query }}"  
    import_role:
      name: add-ocp-inventory       
