- name: Configure Ansible Automation Controller on hub
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - ./vars/vars.yml    
  
  tasks:
  - name: Configure Ansible Automation Controller on hub
    import_role:
      name: "configure-ansible-controller"