- name: Delete Openshift Inventory
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - vars/vars.yml   
    
  tasks:     
  - block:
    - shell: |
        cat /rh/clusters/ocm_subs.txt | awk 'NF'
      register: clusters_list

    - set_fact:
        clusters_list: "{{ clusters_list.stdout_lines | reject('search', 'AWS') | reject('search', 'AZURE')| reject('search', 'GCP') | list }}"

    - shell: |
        kubectl get cd -A  -ojson | jq -r '.items[] | select(.spec.clusterMetadata.infraID == "{{ item }}") | .metadata.name'
      register: cluster_names
      loop: "{{ clusters_list }}"

    - include_role:
        name: delete-ocp-inventory
      vars:
        cluster_name: "{{ item }}"
      loop: "{{ cluster_names | json_query('results[*].stdout') | flatten | select() }}"        
    when: cleanup | bool

  - import_role:
      name: delete-ocp-inventory      
    when: not cleanup | bool 
