- name: Configure GOGS on hub
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - ./vars/vars.yml    

  tasks: 
  - name: Prepare ansible runner host
    include_tasks: tasks/prepare_ansible_runner.yml
    when: not skip_ansible_runner | bool    

  - name: Login cluster
    import_tasks: tasks/login-ocp.yml      

  - name: Query cluster name if not defined
    include_tasks: tasks/query-cluster-details.yml
    when: cluster_name | length < 1    

  - name: Get SA token
    include_tasks: tasks/create-service-account.yml     

  - name: Configure GOGS on {{ cluster }}
    vars:
      cluster: "{{ cluster_name if cluster_name_query is undefined else cluster_name_query }}"  
    import_role:
      name: "deploy-gogs"