- name: Configure GOGS on hub
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - ./vars/vars.yml    
  vars:
    cluster: "{{ ocp_api_url.split('.')[1] }}"
    array: "{{ ocp_api_url.split(':6443')[0] | split('api.') }}" 

  tasks:
  - name: Configure GOGS on {{ cluster }}
    import_role:
      name: "deploy-gogs"