- name: Regenerate CA certificates for the Machine Config Server
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - ./vars/vars.yml  
  vars:
    oc_cmd: "oc410 --insecure-skip-tls-verify"    
  tasks:
  - name: Regenerate CA certificates for the Machine Config Server
    import_role:
      name: regenerate-mcs-certs
