- name: Test
  hosts: localhost
  any_errors_fatal: true 
  vars:
    cluster: "{{ ocp_api_url.split('.')[1] }}"
    rhsm_token: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2ODg2NzQ0MDUsImp0aSI6IjI0NjAzYTJmLTcxNzMtNDFmNy05YmMzLTM3ZjhhZDg5ZmIxZiIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjp0aG5ndXllbkByZWRoYXQuY29tIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6InJoc20tYXBpIiwic2Vzc2lvbl9zdGF0ZSI6ImQ0MzM2N2RiLWQyNjItNDg5Zi1iNGIxLTU0OTBlODJiNzBlYiIsInNjb3BlIjoib2ZmbGluZV9hY2Nlc3MiLCJzaWQiOiJkNDMzNjdkYi1kMjYyLTQ4OWYtYjRiMS01NDkwZTgyYjcwZWIifQ.YYm_rPk5UDGxcapz5kXrO93BpjYkaMNeN7cYD8-iEic"
  
  tasks:
  - name: Generate RHSM refresh token
    block:
    - name: test
      shell: >
        curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token 
        -d grant_type=refresh_token 
        -d client_id=rhsm-api 
        -d refresh_token={{ rhsm_token }} | yq .access_token
      register: refresh_token
      # failed_when: "'null' in refresh_token.stdout" 
      # until: "'null' not in refresh_token"
      until: refresh_token == "null"
      # retries: 10
      # delay: 10      
      become: true    
  
    - debug:
        msg: "{{ refresh_token.stdout }}"