- name: Update spoke CA on hub
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - ./vars/vars.yml  
  vars:
    oc_cmd: "oc410 --insecure-skip-tls-verify"
  tasks:
  - name: Update spoke CA on hub
    import_role:
      name: update-spoke-ca