- name: Test
  hosts: localhost
  any_errors_fatal: true 
  vars_files:
  - vars/vars.yml
  vars:
    cluster: "{{ ocp_api_url.split('.')[1] }}"  
    
  tasks:    
  - name: Prepare ansible runner host
    include_tasks: tasks/prepare_ansible_runner.yml
    when: not skip_ansible_runner | bool    

  - name: Login cluster
    import_tasks: tasks/login-ocp.yml     
    
  - name: Test
    shell: >
      {{ oc_cmd }} process 
      -f roles/update-ocm-cron/defaults/template.yml
      -p API_URL="https://api.o4-ibmvm-01.qe.red-chesterfield.com:6443"
      | oc create -f - -n default 