---
- name: Login openshift at {{ spoke_api_url }}
  shell: |
    oc login -u {{ spoke_user }} -p {{ spoke_pwd }} {{ spoke_api_url }}
  changed_when: true  

- name: Gen new system:masters/admin.kubeconfig
  block:
  - name: Create new admin.kubeconfig
    shell: |   
      oc --insecure-skip-tls-verify config new-admin-kubeconfig > admin.kubeconfig
      sleep 5

  - name: Confirm your new admin.kubeconfig works
    shell: |         
      oc --insecure-skip-tls-verify --kubeconfig=admin.kubeconfig whoami   

  - name: Encode your new kubeconfig
    shell: |         
      cat admin.kubeconfig | base64 -w0   
    register: kubeconfig
  
- name: Logout openshift at {{ spoke_api_url }}
  shell: |
    oc logout
  changed_when: true      
