---
- name: Gen new system:masters/admin.kubeconfig
  environment:
    PATH: "{{ path.stdout }}"
  block:
  - name: Login openshift at {{ ocp_api_url }}
    shell: |
      {{ oc_cmd }} login -u {{ ocp_user }} -p {{ ocp_pwd }} {{ ocp_api_url }}      

  - name: Create new admin.kubeconfig
    shell: |   
      {{ oc_cmd }} config new-admin-kubeconfig > admin.kubeconfig
      sleep 5
      
  - name: Confirm your new admin.kubeconfig works
    shell: |         
      {{ oc_cmd }} --kubeconfig=admin.kubeconfig whoami   
    register: result
    until: result.rc == 0
    retries: 10
    delay: 15
    
  - name: Encode your new kubeconfig
    shell: |         
      cat admin.kubeconfig | base64 -w0   
    register: kubeconfig
  
  - name: Logout openshift at {{ ocp_api_url }}
    shell: |
      {{ oc_cmd }} logout
    changed_when: true      
