---
- name: Install cli tools
  include_role:
    name: common
    tasks_from: install-oc410
  
- name: Generate new admin.kubeconfig for spoke
  import_tasks: gen-kubecfg.yml

- name: Update spoke kubeconfig on hub
  vars:
    spoke_name: "{{ spoke_api_url.split('.')[1] }}"
  environment:
    PATH: "{{ path.stdout }}"    
  block:
  - name: Login openshift on hub at {{ hub_api_url }}
    shell: |
      {{ oc_cmd }} login -u {{ hub_user }} -p {{ hub_pwd }} {{ hub_api_url }}     
  - name: Retrieve your administrator kubeconfig secret name from your managed cluster 
    shell: |
      {{ oc_cmd }} -n {{ spoke_name }} get clusterdeployments {{ spoke_name }} -ojsonpath='{.spec.clusterMetadata.adminKubeconfigSecretRef.name}'
    register: secret_name

  - name: Patch your spoke kubeconfig secret with the new kubeconfig
    shell: >
      {{ oc_cmd }} -n {{ spoke_name }} patch secrets {{ secret_name.stdout }} --type=json 
      -p='[{"op":"replace", "path":"/data/{{ item }}", "value":"{{ kubeconfig.stdout }}"}]'
    with_items:
    - raw-kubeconfig
    - kubeconfig

