---
- name: Create the repo {{ item.split('/') | last }} on gogs server
  block:  
  - name: Get gogs access token
    uri:
      url: http://{{ hostname }}/api/v1/users/{{ gogs_user }}/tokens
      user: "{{ gogs_user }}"
      password: "{{ gogs_user }}"
      method: POST
      body_format: json
      force_basic_auth: true
      status_code: 201
      body:
        name: "sample-token"
        sha1: "8a4fc41b4868aecdd623b10cb1b64a36c6ee51f3"
    register: gogs_access_token

  # - debug:
  #     msg: "{{ gogs_access_token.json.sha1 }}"    
  
  - name: Create the repo {{ item.split('/') | last }} on gogs server
    uri:
      url: http://{{ gogs_user }}:{{ gogs_user}}@{{ hostname }}/api/v1/user/repos?token={{ gogs_access_token.json.sha1 }}
      method: 'POST'
      body_format: json
      status_code: 201
      body:
        name: app-samples
        private: false    

  - name: test
    shell: |
      ls -al /usr/bin | grep pip
      
  # - name: Install tools
  #   shell: |
  #     rpm -ivh {{ rpm_item }}
  #   loop:
  #   - https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/python3-dnf-4.7.0-19.el8.noarch.rpm
  #   - https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/dnf-4.7.0-19.el8.noarch.rpm
  #   - https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/yum-4.7.0-19.el8.noarch.rpm    
  #   loop_control:
  #     loop_var: rpm_item        
   
  - name: Install git
    vars:
      ansible_python_interpreter: "/usr/bin/python3.9"  
    yum:
      name: 
        - git
      state: present     



  # - name: Clone the repo {{ item.split('/') | last }} to local
  #   git:
  #     repo: "{{ item }}"
  #     dest: app-samples
  #     bare: true
  #     clone: true
  #     force: true
  #     update: true      
  
  # - name: Push the repo {{ item.split('/') | last }} to gogs server
  #   shell: |
  #     cd {{ item.split('/') | last }}
  #     git push --mirror 'http://{{ gogs_user }}:{{ gogs_user}}@{{ hostname }}/{{ gogs_user }}/app-samples'
  #     rm -rf {{ item.split('/') | last }}

