  - name: Generate gogs server access token
    uri:
      url: https://gogs-{{ hostname }}/api/v1/users/{{ gogs_user }}/tokens
      user: "{{ gogs_user }}"
      password: "{{ gogs_user }}"
      method: POST
      body_format: json
      force_basic_auth: true
      status_code: 201
      validate_certs: no
      body:
        name: "sample-token"
        sha1: "8a4fc41b4868aecdd623b10cb1b64a36c6ee51f3"
    register: gogs_access_token

  - name: Push generated token to secret/gogs-admin-token in {{ gogs_ns }} namespace
    shell: |
      {{ oc_cmd }} apply -f - <<EOF
        kind: Secret
        apiVersion: v1
        metadata:
          name: gogs-admin-token
          namespace: {{ gogs_ns }}
        data:
          token: {{ gogs_access_token.json.sha1|b64encode }}
        type: Opaque
      EOF            
    changed_when: true 
    
  # - debug:
  #     msg: "{{ gogs_access_token.json.sha1 }}" 