- name: Create ClusterCatalog acm-dev-catalog
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: olm.operatorframework.io/v1
      kind: ClusterCatalog
      metadata:
        labels:
          olm.operatorframework.io/metadata.name: acm-dev-catalog
        name: acm-dev-catalog
      spec:
        availabilityMode: Available
        priority: 0
        source:
          image:
            ref: quay.io:443/acm-d/acm-dev-catalog:{{ acm_snapshot_tag | default('latest-5.0') }}
          type: Image 
  when: not (mce_only | default(false) | bool)   

- name: Create ClusterCatalog mce-dev-catalog
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: olm.operatorframework.io/v1
      kind: ClusterCatalog
      metadata:
        labels:
          olm.operatorframework.io/metadata.name: mce-dev-catalog
        name: mce-dev-catalog
      spec:
        availabilityMode: Available
        priority: 0
        source:
          image:
            ref: quay.io:443/acm-d/mce-dev-catalog:{{ mce_snapshot_tag | default('latest-5.0') }}
          type: Image

- name: Wait for ClusterCatalogs to be running
  kubernetes.core.k8s_info:
    api_version: olm.operatorframework.io/v1
    kind: ClusterCatalog
    name: "{{ item.name }}"
  register: clustercatalog_results
  until: 
    - clustercatalog_results.resources | length > 0
    - clustercatalog_results.resources[0].status is defined
    - clustercatalog_results.resources[0].status.conditions is defined
    - clustercatalog_results.resources[0].status.conditions | selectattr('type', 'equalto', 'Serving') | selectattr('status', 'equalto', 'True') | list | length > 0
  retries: 4
  delay: 15  
  loop:
    - { name: 'mce-dev-catalog', included: True }
    - { name: 'acm-dev-catalog', included: "{{ not mce_only|bool }}"}
  when: item.included
