- name: Login openshift at {{ ocp_api_url }}
  shell: |
    {{ oc_cmd }} login -u {{ ocp_user }} -p {{ ocp_pwd }} {{ ocp_api_url }}     
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 30 
