---
- name: Install cli tools
  include_role:
    name: common
    tasks_from: install-oc410

- name: Regenerate the CA/cert and automatically rotate the user-data
  environment:
    PATH: "{{ path.stdout }}"
  block:    
  - name: Login openshift at {{ ocp_api_url }}
    shell: |
      {{ oc_cmd }} login -u {{ ocp_user }} -p {{ ocp_pwd }} {{ ocp_api_url }}
    changed_when: true    

  - name: Identify infrastructure provider
    shell: |
      {{ oc_cmd }} -n openshift-machine-api get secret/master-user-data | awk '{ if (NR>1) print $1 }'| wc -l
    register: sc_count
    ignore_errors: true

  - name: Regenerate the CA/cert and automatically rotate the user-data
    block:
    - name: Regenerate the CA/cert and automatically rotate the user-data for cloud infrastructure
      shell: |
        {{ oc_cmd }} adm ocp-certificates regenerate-machine-config-server-serving-cert
      when: sc_count.stdout == "1"

    - name: Regenerate the CA/cert and automatically rotate the user-data for bm
      block:
      - name: Regenerate command without updating the user-data secrets
        shell: |
          {{ oc_cmd }} adm ocp-certificates regenerate-machine-config-server-serving-cert --update-ignition=false

      - name: Find the updated MCS CA cert
        shell: |
          {{ oc_cmd }} -n openshift-machine-config-operator get secret/machine-config-server-ca 
          -o=jsonpath='{.data.tls\.crt}'       
        register: ca_cert
          
      - name: Update ignition with new cert
        block:
        - name: Get user data from secret/worker-user-data-managed
          shell: >       
            {{ oc_cmd }} -n openshift-machine-api get secret/worker-user-data-managed 
            -o=jsonpath='{.data.userData}' | base64 -d
          register: user_data
        
        - name: Replace ca cert 
          shell: |
            echo $user_data | sed -e 's/data:text.*/{{ ca_cert.stdout }}"}]/g'
          register: user_data_updated
        
        - name: Update ignition with new ca cert
          shell: >
            echo 'inside'
            # {{ oc_cmd }} -n openshift-machine-api patch secrets worker-user-data-managed --type=json 
            # -p='[{"op":"replace", "path":"/data/tls/.crt", "value":"{{ user_data_updated.stdout|b64encode }}"}]'          
      when: sc_count.stdout == "0"      