- name: Cleanup existing resources if any
  shell: |
    {{ oc_cmd }} -n default delete imagestream --all
    {{ oc_cmd }} -n default delete buildconfig --all
    {{ oc_cmd }} -n default delete cronjob --all
  ignore_errors: true

- name: Apply cronjob template
  shell: >
    {{ oc_cmd }} process 
    -f roles/acm-cronjob/defaults/template.yml
    -p API_URL={{ ocp_api_url }}
    -p OCM_TOKEN={{ rhocm_token }}
    | oc create -f - -n default 

- name: Wait for cronjob succeeded
  shell: >
    {{ oc_cmd }} get cronjob -n default acm-cronjob -ojson 
    | jq -r .status.lastSuccessfulTime
  register: last_success
  until: last_success.stdout != 'null'
  retries: 10
  delay: 30
       

  
  