- name: Enable Openshift image registry
  shell: |
    {{ oc_cmd }} patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed"}}'
    {{ oc_cmd }} patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'

- name: Cleanup existing resources if any
  shell: |
    {{ oc_cmd }} -n default delete imagestream --all
    {{ oc_cmd }} -n default delete buildconfig --all
    {{ oc_cmd }} -n default delete cronjob --all
  ignore_errors: true

- name: Apply cronjob template
  shell: >
    {{ oc_cmd }} process 
    -f roles/acm-cronjob/defaults/template.yml
    -p API_URL={{ ocp_api_url }}
    -p OCM_TOKEN={{ rhocm_token }}
    | oc create -f - -n default 


  
  