---
- name: Add ansible project
  block:
  - name: Read secret file
    include_vars: "vault-files/acmqe-ansible-key.yml"

  - name: Create SCM credential from a private_key file
    awx.awx.credential:
      controller_username: "admin"
      controller_password: "{{ aap_pwd.stdout }}"
      controller_host: "https://{{ aap_url.stdout }}"      
      validate_certs: false           
      name: "{{ project_name }}"
      organization: Default
      state: present
      credential_type: Source Control
      inputs:
        ssh_key_data: "{{ key }}"

  - name: Create project {{ project_name }}
    awx.awx.project:
      controller_username: "admin"
      controller_password: "{{ aap_pwd.stdout }}"
      controller_host: "https://{{ aap_url.stdout }}"       
      validate_certs: false 
      name: "{{ project_name }}"
      description: "ACM QE ansible playbooks"
      organization: "Default"
      scm_type: "git"
      scm_branch: "{{ project_repo_branch }}"
      scm_clean: true
      scm_update_on_launch: true
      scm_url: "{{ project_repo_url }}"
      credential: "{{ project_name }}"
      state: present
