---
  - name: Copy task modules to remote
    copy:
      src: '.'
      dest: '.'
      follow: yes
      remote_src: true 

  - name: Create AAP controller CR
    shell: |
      {{ oc_cmd }} apply -f - <<EOF
        apiVersion: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        metadata:
          name: {{ aap_name }}
          namespace: {{ aap_project }}
        spec:
          replicas: 1
      EOF            
    changed_when: true     

  - name: Get AAP route
    shell: |
      {{ oc_cmd }}  get route -n {{ aap_project }} | grep {{ aap_name }} | awk '{ print $2 }'
    changed_when: true    
    register: aap_url
    until: aap_url.stdout != ''
    retries: 15
    delay: 30

  - name: Print AAP route
    debug:
      msg: "{{ aap_url.stdout }}"    
    
  - name: Wait for aap web ready
    shell: |
      curl -k https://{{ aap_url.stdout }}/migrations_notran --fail --show-error 
    changed_when: true    
    register: resp
    until: resp.rc == 0
    retries: 15
    delay: 30

  - name: Get AAP admin password 
    shell: |
      {{ oc_cmd }} -n {{ aap_project }} get secret/{{ aap_name }}-admin-password -oyaml | grep password: | tail -n1 | awk '{ print $2}' | base64 -d
    changed_when: true    
    register: aap_pwd  

  - name: Download AAP subscription manifest file from RHSM and apply license
    import_tasks: apply-aap-license.yml

  - name: Create a new token using username/password
    awx.awx.token:
      description: 'admin-token'
      scope: "write"
      state: present
      controller_username: "admin"
      controller_password: "{{ aap_pwd.stdout }}"
      controller_host: "https://{{ aap_url.stdout }}"    
      validate_certs: false  
    register: aap_token   

  - name: Push admin token to secret/{{aap_name}}-admin-token
    shell: |
      {{ oc_cmd }} apply -f - <<EOF
        kind: Secret
        apiVersion: v1
        metadata:
          name: {{ aap_name }}-admin-token
          namespace: aap
        data:
          token: {{ aap_token.ansible_facts.tower_token.token|b64encode }}
        type: Opaque
      EOF            
    changed_when: true        

  - name: Update demo job template for prompt on launch 
    awx.awx.job_template:
      name: 'Demo Job Template'
      project: 'Demo Project'
      ask_variables_on_launch: true
      state: present
      controller_username: "admin"
      controller_password: "{{ aap_pwd.stdout }}"
      controller_host: "https://{{ aap_url.stdout }}"    
      validate_certs: false  
    register: update_result
    until: update_result is not failed
    retries: 5
    delay: 15      

  - name: Create ansible project
    import_tasks: add-ansible-project.yml      