---
  - name: Generate certs
    shell: |
      openssl genrsa -out rootCA.key 4096
      openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.crt -config ca.conf
      openssl genrsa -out server.key 4096
      openssl req -new -key server.key -out server.csr -config ca.conf
      openssl x509 -req -in server.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out server.crt -days 500 -sha256 -extfile san.ext
      