---
- name: Login openshift
  shell: |
    {{ oc_cmd }} login -u {{ ocp_user }} -p {{ ocp_pwd }} {{ ocp_api_url }}
  changed_when: true        

- name: Check if service account for automation exist
  shell: |
    {{ oc_cmd }} get serviceaccount {{ sa }} -n {{ sa_ns }}
  changed_when: true  
  register: sa_count
  ignore_errors: true

- name: Create service account for automation
  shell: |
    {{ oc_cmd }} create serviceaccount {{ sa }} -n {{ sa_ns }}
    {{ oc_cmd }} adm policy add-cluster-role-to-user cluster-admin -z {{ sa }}
  changed_when: true  
  when: sa_count.rc > 0

- name: Get service account token
  block:
  - name: Get secret associated with the service account
    shell: >
      {{ oc_cmd }} -n {{ sa_ns }} get serviceaccount {{ sa }} -o json 
      | jq '.secrets' 
      | grep automation-service-account-token | xargs | awk -F': ' '{print $NF}' 
    register: sc_name  

  - name: Extract sa token from secret
    shell: |
      {{ oc_cmd }} -n {{ sa_ns }} get secret {{ sc_name.stdout }} -o json | jq '.data.token' | xargs | base64 --decode 
    register: sa_token
